# This is a basic workflow that is manually triggered

name: Run pre-commit

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [develop-16.0]

jobs:
  pre-commit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.0
